extensions:
  health_check:
    endpoint: 127.0.0.1:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  batch:
    timeout: 2s
    send_batch_size: 512
    send_batch_max_size: 1024

exporters:
  file/traces:
    path: ${env:OTEL_FILE_DIR}/traces.json
    create_directory: true
    format: json
    rotation:
      max_megabytes: 100
      max_days: 7
      max_backups: 20
  file/metrics:
    path: ${env:OTEL_FILE_DIR}/metrics.json
    create_directory: true
    format: json
    rotation:
      max_megabytes: 100
      max_days: 7
      max_backups: 20
  file/logs:
    path: ${env:OTEL_FILE_DIR}/logs.json
    create_directory: true
    format: json
    rotation:
      max_megabytes: 100
      max_days: 7
      max_backups: 20

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: info
      encoding: json
    metrics:
      level: normal
      readers:
        - pull:
            exporter:
              prometheus:
                host: 127.0.0.1
                port: 8888
                without_scope_info: true
                without_type_suffix: true
                without_units: true
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [file/traces]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [file/metrics]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [file/logs]
